In [2]:
import numpy as np
from scipy.sparse import csr_matrix

In [5]:
A = csr_matrix([[1, 2, 0], [0, 0, 3], [4, 0, 5]])

In [7]:
A

<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [8]:
v = np.array([1, 0, -1])

In [9]:
v

array([ 1,  0, -1])

In [10]:
A.dot(v)

array([ 1, -3, -1])

In [11]:
np.dot(A.toarray(), v)

array([ 1, -3, -1])

In [12]:
from scipy.sparse import lil_matrix
from scipy.sparse.linalg import spsolve
from numpy.linalg import solve, norm
from numpy.random import rand

In [13]:
A = lil_matrix((1000, 1000))

In [14]:
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in List of Lists format>

In [18]:
A[0, :100] = rand(100)
A[1, 100:200] = A[0, :100]
A.setdiag(rand(1000))

In [19]:
A = A.tocsr()
b = rand(1000)
x = spsolve(A, b)

In [22]:
x

array([ 7.28938592e+01, -1.86676421e+02,  2.24406810e-01,  3.85451155e+00,
        3.68047381e+00,  8.86880348e-01,  2.35482770e-01,  3.46057070e+00,
        9.75829357e-01,  1.20608966e+00,  8.27758415e-01,  3.88434143e-01,
        4.38029058e-01,  8.30540235e-01,  9.63160098e-01,  9.77857526e-01,
        1.05685726e+00,  1.13061686e+01,  4.27432698e+00,  7.36940027e-01,
        1.43688316e+00,  3.17840267e-02,  1.10822727e+00,  7.87601167e-01,
        1.12466010e+00,  1.09322591e+00,  2.44597232e+00,  1.40210881e-01,
        1.22346342e+00,  1.52531494e+01,  1.37411057e+00,  2.86281253e-01,
        1.11854223e+00,  9.38018871e-02,  8.47780444e-01,  2.20986699e+00,
        1.58387375e+00,  2.62714871e-01,  1.29956910e+01,  8.17777208e-01,
        8.30331627e-01,  5.26700954e+00,  1.15279310e+00,  2.48283228e+00,
        8.89392998e-01,  9.60332460e-01,  9.11685561e-01,  4.56753416e-01,
        9.96722566e-01,  2.12222217e-01,  1.00322322e+01,  7.95043533e-01,
        1.70805760e+00,  

In [23]:
x_ = solve(A.toarray(), b)

In [24]:
x_

array([ 7.28938592e+01, -1.86676421e+02,  2.24406810e-01,  3.85451155e+00,
        3.68047381e+00,  8.86880348e-01,  2.35482770e-01,  3.46057070e+00,
        9.75829357e-01,  1.20608966e+00,  8.27758415e-01,  3.88434143e-01,
        4.38029058e-01,  8.30540235e-01,  9.63160098e-01,  9.77857526e-01,
        1.05685726e+00,  1.13061686e+01,  4.27432698e+00,  7.36940027e-01,
        1.43688316e+00,  3.17840267e-02,  1.10822727e+00,  7.87601167e-01,
        1.12466010e+00,  1.09322591e+00,  2.44597232e+00,  1.40210881e-01,
        1.22346342e+00,  1.52531494e+01,  1.37411057e+00,  2.86281253e-01,
        1.11854223e+00,  9.38018871e-02,  8.47780444e-01,  2.20986699e+00,
        1.58387375e+00,  2.62714871e-01,  1.29956910e+01,  8.17777208e-01,
        8.30331627e-01,  5.26700954e+00,  1.15279310e+00,  2.48283228e+00,
        8.89392998e-01,  9.60332460e-01,  9.11685561e-01,  4.56753416e-01,
        9.96722566e-01,  2.12222217e-01,  1.00322322e+01,  7.95043533e-01,
        1.70805760e+00,  

In [26]:
#!pip install kdtree

In [27]:
import kdtree

In [28]:
emptyTree = kdtree.create(dimensions=3)

In [29]:
emptyTree

<KDNode - None>

In [30]:
point1 = (2, 3, 4)

In [31]:
point2 = [4, 5, 6]

In [32]:
import collections
Point = collections.namedtuple('Point', 'x y z')


In [34]:
Point

__main__.Point

In [35]:
point3 = Point(5, 3, 2)

In [36]:
point3

Point(x=5, y=3, z=2)

In [37]:
tree = kdtree.create([point1, point2, point3])

In [38]:
tree

<KDNode - [4, 5, 6]>

In [39]:
ndim = data.shape[0]

NameError: name 'data' is not defined